// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using disease_outbreaks_detector.Models;

#nullable disable

namespace disease_outbreaks_detector.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251011151715_InitialCreate3")]
    partial class InitialCreate3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("disease_outbreaks_detector.Models.CaseRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cases")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Critical")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("Recovered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TodayCases")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TodayDeaths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TodayRecovered")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("population")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CaseRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
